name: py36
channels:
  - bashtage
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - arch=4.15
  - blas=1.0
  - icc_rt=2019.0.0
  - intel-openmp=2020.0
  - joblib=0.14.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - liblapack=3.8.0
  - mkl=2019.5
  - mkl-service=2.3.0
  - numpy=1.18.1
  - pip=20.0.2
  - python=3.6.5
  - python_abi=3.6
  - scipy=1.3.1
  - six=1.14.0
  - ujson=2.0.1
  - vc=14.1
  - vs2015_runtime=15.5.2
  - wheel=0.34.2
  - wincertstore=0.2
  - pip:
    - absl-py==0.9.0
    - alabaster==0.7.12
    - alembic==1.4.1
    - appdirs==1.4.4
    - astor==0.8.1
    - astroid==2.3.3
    - astropy==4.0
    - atomicwrites==1.3.0
    - attr==0.3.1
    - attrs==19.3.0
    - autogluon==0.0.5
    - autonormalize==1.0.1
    - babel==2.8.0
    - backcall==0.1.0
    - bcrypt==3.1.7
    - black==19.10b0
    - bleach==3.1.1
    - blis==0.4.1
    - bootstrapped==0.0.2
    - boruta==0.3
    - boto==2.49.0
    - boto3==1.9.187
    - botocore==1.12.253
    - catalogue==1.0.0
    - catboost==0.22
    - categorical-encoding==0.3.0
    - category-encoders==2.1.0
    - causalnex==0.8.1
    - certifi==2019.11.28
    - cffi==1.14.0
    - chardet==3.0.4
    - cleanlab==0.1.1
    - click==7.0
    - cliff==3.0.0
    - cloudpickle==1.3.0
    - cmd2==0.8.9
    - cmdstanpy==0.4.0
    - colorama==0.4.3
    - colorlog==4.1.0
    - configparser==4.0.2
    - confuse==1.0.0
    - convertdate==2.2.0
    - cryptography==2.9
    - cycler==0.10.0
    - cymem==2.0.3
    - cython==0.29.15
    - dask==2.12.0
    - databricks-cli==0.9.1
    - dataclasses==0.7
    - deap==1.3.1
    - decorator==4.4.2
    - defusedxml==0.6.0
    - dill==0.3.1.1
    - diskcache==5.0.3
    - distributed==2.12.0
    - docker==4.2.0
    - docutils==0.15.2
    - entrypoints==0.3
    - ephem==3.7.7.1
    - featuretools==0.13.3
    - featuretools-sklearn-transformer==0.1.0
    - featuretools-tsfresh-primitives==0.2.1
    - featuretools-update-checker==1.0.2
    - filelock==3.0.12
    - fire==0.3.1
    - flask==1.1.1
    - future==0.18.2
    - gast==0.2.2
    - gensim==3.8.1
    - gitdb==4.0.2
    - gitpython==3.1.0
    - google-pasta==0.1.8
    - googleapis-common-protos==1.51.0
    - gorilla==0.3.0
    - grpcio==1.27.2
    - h5py==2.10.0
    - heapdict==1.0.1
    - holidays==0.10.1
    - htmlmin==0.1.12
    - idna==2.6
    - imagesize==1.2.0
    - importlib-metadata==1.5.0
    - ipykernel==5.1.4
    - ipython==7.13.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - isort==4.3.21
    - itsdangerous==1.1.0
    - jedi==0.16.0
    - jinja2==2.11.1
    - jmespath==0.9.5
    - json-spec==0.10.1
    - jsoncomment==0.4.2
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.0.0
    - jupyter-console==6.1.0
    - jupyter-core==4.6.3
    - kaggle==1.5.6
    - keras==2.3.1
    - keras-applications==1.0.8
    - keras-contrib==2.0.8
    - keras-mdn-layer==0.2.1
    - keras-preprocessing==1.1.0
    - kiwisolver==1.1.0
    - kmodes==0.10.2
    - lazy-object-proxy==1.4.3
    - lightgbm==2.3.0
    - llvmlite==0.31.0
    - lunarcalendar==0.0.9
    - mako==1.1.2
    - markdown==3.2.1
    - markupsafe==1.1.1
    - matplotlib==3.1.3
    - mccabe==0.6.1
    - missingno==0.4.2
    - mistune==0.8.4
    - mlflow==1.7.1
    - more-itertools==8.2.0
    - msgpack==1.0.0
    - murmurhash==1.0.2
    - nbconvert==5.5.0
    - nbformat==5.0.4
    - nbsphinx==0.4.2
    - networkx==2.4
    - nlp-primitives==0.2.4
    - nltk==3.4.5
    - notebook==6.0.3
    - numba==0.48.0
    - numexpr==2.7.1
    - opt-einsum==3.1.0
    - optuna==1.1.0
    - packaging==20.3
    - pandas==0.25.3
    - pandas-profiling==2.5.0
    - pandocfilters==1.4.2
    - paramiko==2.7.1
    - parso==0.6.2
    - pathspec==0.8.0
    - patsy==0.5.1
    - pbr==5.4.4
    - pgmpy==0.1.6
    - phik==0.9.9
    - pickleshare==0.7.5
    - pillow==6.2.1
    - plac==1.1.3
    - plotly==4.5.4
    - pluggy==0.13.1
    - portalocker==1.7.0
    - preshed==3.0.2
    - prettytable==0.7.2
    - prometheus-client==0.7.1
    - prometheus-flask-exporter==0.13.0
    - promise==2.3
    - prompt-toolkit==3.0.4
    - protobuf==3.11.3
    - psutil==5.7.0
    - py==1.8.1
    - pyaml==20.3.1
    - pyarrow==2.0.0
    - pycparser==2.20
    - pydantic==1.4
    - pygments==2.6.1
    - pylint==2.4.4
    - pymeeus==0.3.7
    - pynacl==1.3.0
    - pyparsing==2.4.6
    - pyperclip==1.7.0
    - pypiwin32==223
    - pyreadline==2.1
    - pyro-ppl==1.5.0
    - pyrsistent==0.15.7
    - pystan==2.19.1.1
    - pytest==5.4.0
    - pytest-pylint==0.15.1
    - python-dateutil==2.8.0
    - python-editor==1.0.4
    - python-graphviz==0.8.4
    - python-slugify==4.0.0
    - pytz==2019.3
    - pywin32==227
    - pywinpty==0.5.7
    - pyyaml==5.3
    - pyzmq==19.0.0
    - qtconsole==4.7.1
    - qtpy==1.9.0
    - querystring-parser==1.2.4
    - regex==2020.2.20
    - requests==2.22.0
    - retrying==1.3.3
    - s3transfer==0.2.1
    - sacremoses==0.0.38
    - scikit-learn==0.23.2
    - scikit-optimize==0.7.4
    - seaborn==0.10.0
    - send2trash==1.5.0
    - sentence-transformers==0.2.5
    - sentencepiece==0.1.85
    - setuptools==45.2.0
    - setuptools-git==1.2
    - shap==0.35.0
    - simplejson==3.17.0
    - sklearn==0.0
    - smart-open==1.9.0
    - smmap==3.0.1
    - snowballstemmer==2.0.0
    - sortedcontainers==2.1.0
    - spacy==2.2.3
    - sphinx==2.4.4
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - spyder-kernels==0.5.2
    - sqlalchemy==1.3.13
    - sqlparse==0.3.1
    - srsly==1.0.2
    - statsmodels==0.11.1
    - stevedore==1.32.0
    - stopit==1.1.2
    - tabulate==0.8.6
    - tangled-up-in-unicode==0.0.3
    - tblib==1.6.0
    - tensorboard==1.15.0
    - tensorflow==1.15.2
    - tensorflow-datasets==3.0.0
    - tensorflow-estimator==1.15.1
    - tensorflow-hub==0.7.0
    - tensorflow-metadata==0.21.2
    - tensorflow-probability==0.7.0
    - termcolor==1.1.0
    - terminado==0.8.3
    - testpath==0.4.4
    - text-unidecode==1.3
    - thinc==7.3.1
    - threadpoolctl==2.1.0
    - tokenizers==0.0.11
    - toml==0.10.0
    - toolz==0.10.0
    - torch==1.6.0+cpu
    - torchtext==0.5.0
    - torchvision==0.5.0
    - tornado==6.0.4
    - tpot==0.11.1
    - tqdm==4.42.0
    - traitlets==4.3.3
    - tsfresh==0.14.1
    - typed-ast==1.4.1
    - typing==3.7.4.1
    - umap-learn==0.3.10
    - update-checker==0.16
    - urllib3==1.22
    - versioneer==0.18
    - visions==0.2.2
    - waitress==1.4.3
    - wasabi==0.6.0
    - wcwidth==0.1.8
    - webencodings==0.5.1
    - websocket-client==0.57.0
    - werkzeug==1.0.0
    - widgetsnbextension==3.5.1
    - wrapt==1.11.2
    - zict==2.0.0
    - zipp==3.1.0

